@startuml

top to bottom direction
skinparam linetype ortho
class MonthPayoff {
- Long id
- LocalDate payoffDate
- BigDecimal waterHeatingUnitCost
- BigDecimal centralHeatingUnitCost
- BigDecimal hotWaterConsumption
- Place place
- Owner owner
}
class Place {
- Long id
- Short placeNumber
- BigDecimal area
- Boolean hotWaterConnection
- Boolean centralHeatingConnection
- BigDecimal predictedHotWaterConsumption
- List<Advance> advances
- Building building
- Owner owner
- List<HotWaterEntry> hotWaterEntries
- List<MonthPayoff> monthPayoffs
- List<AnnualBalance> annualBalances
+ String messageToSign()
}
class Building {
- Long id
- BigDecimal totalArea
- BigDecimal communalAreaAggregate
- Address address
- List<Place> places
- HeatDistributionCentre heatDistributionCentre
+ String messageToSign()
}
class Address {
- Long id
- String street
- String buildingNumber
- String city
- String postalCode
}
class Owner {
- String phoneNumber
+ boolean equals(Object)
+ int hashCode()
+ String messageToSign()
}
class HotWaterAdvance {
- BigDecimal hotWaterAdvanceValue
}
class HotWaterEntry {
- Long id
- LocalDate date
- BigDecimal entryValue
- Place place
- Manager manager
+ String messageToSign()
}
class PastQuarterHotWaterPayoff {
- Place id
- BigDecimal averageConsumption
- Integer daysNumberInQuarter
}
class Manager {
- String license
+ String messageToSign()
}
class HeatDistributionCentre {
- Long id
- List<Building> buildings
- List<HeatDistributionCentrePayoff> heatDistributionCentrePayoffs
}
abstract class Advance {
# Long id
# LocalDate date
# Place place
}
class HeatDistributionCentrePayoff {
- Long id
- LocalDate date
- BigDecimal consumption
- BigDecimal consumptionCost
- BigDecimal heatingAreaFactor
- HeatDistributionCentre heatDistributionCentre
- Manager manager
}
class AnnualBalance {
- Long id
- Short year
- BigDecimal totalHotWaterAdvance
- BigDecimal totalHeatingPlaceAdvance
- BigDecimal totalHeatingCommunalAreaAdvance
- BigDecimal totalHotWaterCost
- BigDecimal totalHeatingPlaceCost
- BigDecimal totalHeatingCommunalAreaCost
- Place place
}
class HeatingPlaceAndCommunalAreaAdvance {
- BigDecimal heatingPlaceAdvanceValue
- BigDecimal heatingCommunalAreaAdvanceValue
- BigDecimal advanceChangeFactor
+ String messageToSign()
}

  Owner "1" -- "many" HotWaterEntry
  Manager "1" -- "many" HotWaterEntry
  Manager "many" -- "1" HeatDistributionCentrePayoff
  Building "1" *-- "many" Place
  Place "1" -- "many" MonthPayoff
  Place "1" -- "many" Advance
  Place "1" -- "many" AnnualBalance
  Place "1" -- "many" HotWaterEntry
  Advance  <|--  HotWaterAdvance
  Advance <|--  HeatingPlaceAndCommunalAreaAdvance
  PastQuarterHotWaterPayoff "1" -- "1" Place
  HeatDistributionCentre "1" -- "many" HeatDistributionCentrePayoff
  HeatDistributionCentre "1" o-- "many" Building
  Building "1" *-- "1" Address

@enduml