@startuml

left to right direction
skinparam linetype ortho
class MonthPayoff {
- Long id
- LocalDate payoffDate
- BigDecimal waterHeatingUnitCost
- BigDecimal centralHeatingUnitCost
- BigDecimal hotWaterConsumption
}
class Owner {
}
class Place {
- Long id
- Short placeNumber
- BigDecimal area
- Boolean hotWaterConnection
- Boolean centralHeatingConnection
- BigDecimal predictedHotWaterConsumption
+ String messageToSign()
}
class Building {
- Long id
- BigDecimal totalArea
- BigDecimal communalAreaAggregate
+ String messageToSign()
}
class Address {
- Long id
- String street
- String buildingNumber
- String city
- String postalCode
}
class HotWaterAdvance {
- BigDecimal hotWaterAdvanceValue
}
class HotWaterEntry {
- Long id
- LocalDate date
- BigDecimal entryValue
+ String messageToSign()
}
class PastQuarterHotWaterPayoff {
- Place id
- BigDecimal averageConsumption
- Integer daysNumberInQuarter
}
class Manager {
}
class HeatDistributionCentre {
- Long id
}
abstract class Advance {
# Long id
# LocalDate date
# Place place
}
class HeatDistributionCentrePayoff {
- Long id
- LocalDate date
- BigDecimal consumption
- BigDecimal consumptionCost
- BigDecimal heatingAreaFactor
}
class AnnualBalance {
- Long id
- Short year
- BigDecimal totalHotWaterAdvance
- BigDecimal totalHeatingPlaceAdvance
- BigDecimal totalHeatingCommunalAreaAdvance
- BigDecimal totalHotWaterCost
- BigDecimal totalHeatingPlaceCost
- BigDecimal totalHeatingCommunalAreaCost
- Place place
}
class HeatingPlaceAndCommunalAreaAdvance {
- BigDecimal heatingPlaceAdvanceValue
- BigDecimal heatingCommunalAreaAdvanceValue
- BigDecimal advanceChangeFactor
+ String messageToSign()
}

  Owner "1" -- "many" HotWaterEntry
  Manager "1" -- "many" HotWaterEntry
  Manager "many" -- "1" HeatDistributionCentrePayoff
  Building "1" *-- "many" Place
  Place "1" -- "many" MonthPayoff
  Place "1" -- "many" Advance
  Place "1" -- "many" AnnualBalance
  Place "1" -- "many" HotWaterEntry
  Advance  <|--  HotWaterAdvance
  Advance <|--  HeatingPlaceAndCommunalAreaAdvance
  PastQuarterHotWaterPayoff "1" -- "1" Place
  HeatDistributionCentre "1" -- "many" HeatDistributionCentrePayoff
  HeatDistributionCentre "1" o-- "many" Building
  Building "1" *-- "1" Address

  note left of Manager
    Manager, Owner is placed in MOK class diagram
  end note

  note right of HeatingPlaceAndCommunalAreaAdvance
  advanceChangeFactor is inserted once per quarter
  end note


  note right of Building
  communalAreaAggregate = totalArea - sum(Place.area)
  end note

  note left of Place
  Place can have following types of connection:
    - hot water connection,
    - central heating connection,
    - hot water connection and central heating connection,
    - no connection.
  end note
    legend top
    All classes in MOW extend AbstractEntity. Implementation of AbstractEntity Class is placed in MOK.
    All classes use Lombok for constructors, getters and setters.
    end legend


@enduml