  @startuml
    left to right direction

    actor Zarządca as z

    rectangle MOW {
    usecase "16. Dodanie budynku" as MOW16
    usecase "15. Dodanie lokalu w budynku" as MOW15
    usecase "12. Wprowadzenie rzeczywistego \n zużycia wodomierza ciepłej wody" as MOW12
    usecase "14. Wprowadzenie predykcji zużycia \n wodomierza ciepłej wody" as MOW14
    usecase "13. Wprowadzenie danych z faktury wraz\n z współczynnikiem podziału zużycia" as MOW13
    usecase "17. Modyfikowanie właściciela lokalu" as MOW17
    usecase "18. Modyfikowanie lokalu w budynku" as MOW18
    usecase "5. Modyfikowanie lokalu w budynku" as MOW5
    usecase "24. Wyświetlenie wielkości zaliczki \n na poczet ogrzewania powierzchni lokalu" as MOW24
    usecase "21. Wyświetlenie wielkości zaliczki \n na poczet ogrzewania części wspólnej" as MOW21
    usecase "23. Wyświetlenie wielkości zaliczki \n na poczet ogrzewania wody" as MOW23
    usecase "12. Wprowadzenie rzeczywistego \n zużycia wodomierza ciepłej wody" as MOW12
    usecase "7. Wyświetlenie wielkości zaliczek" as MOW7
    usecase "11. Wprowadzenie współczynnika modyfikacji wielkości zaliczki" as MOW11
    usecase "6. Wyświetlanie listy budynków \n podłączonych do węzła" as MOW6
    usecase "5. Wyświetlanie listy lokali w budynku" as MOW5
    usecase "4. Wyświetlenie parametrów węzła" as MOW4
    usecase "2. Wyświetlenie raportu" as MOW2
    usecase "3. Wyświetlenie raportów" as MOW3
    usecase "1. Wyświetlenie jednostkowego kosztu ogrzania" as MOW1
    usecase "9. Wyświetlenie lokalu" as MOW9
    usecase "22. Obliczenie miesięcznego rozliczenia dla lokalu" as MOW22
    }

  MOW6 <.. MOW16: <<extend>>
  MOW4 <.. MOW13: <<extend>>
  MOW13 ..> MOW22: <<include>>
  MOW5 <.. MOW15: <<extend>>
  MOW9 <.. MOW12: <<extend>>
  MOW9 <.. MOW14: <<extend>>
  MOW9 <.. MOW17: <<extend>>
  MOW9 <.. MOW18: <<extend>>

  MOW2 ..> MOW7: <<include>>
  MOW3 <.. MOW2: <<extend>>

  MOW7 ..> MOW24: <<include>>
  MOW7 ..> MOW21: <<include>>
  MOW7 ..> MOW23: <<include>>

  MOW6 ..> MOW5: <<include>>
  MOW5 <.. MOW9: <<extend>>
  MOW5 ..> MOW11: <<include>>
  MOW6 <.. MOW3: <<extend>>

    z -- MOW4
    z -- MOW6
    z -- MOW1

    @enduml
